[package]
name = "seleste_v1"
version = "0.1.0"
edition = "2024"

[dependencies]
rpassword = "7.0"       # For secure password input
colored = "2.0"         # For colored terminal output
dialoguer = "0.11"      # For interactive menus
